
# Introduction

#### Abstract {-}

Although R began as a specialist statistical programming language, the R ecosystem has grown wildly over the past few years making it a viable general-purpose research environment across the whole research lifecycle.

Survey research datasets come from a diverse range of sources, often containing richer metadata than your average data frame. This workshop provides a practical demonstration of several packages for accessing and working with survey data, associated metadata and official statistics in R.

We will demonstrate:

* Working with external data sources from common statistical packages (SPSS, SAS, Stata, Excel) and their quirks

* Easily working with categorical data in R with the “labelled” R package

* A brief introduction to the “tidy data” concept (https://tidyr.tidyverse.org/articles/tidy-data.html) and its application to survey research data

* Accessing external databases in an R native way using DBI and dbplyr

* Accessing publicly accessible data in R scripts via the web

* Resources for accessing official statistics data in R

Participants should have a basic working knowledge of R to follow along with examples, but beginners are also welcome.
